### ISSUE TITLE
Bump Mermaid JS

### ISSUE THREAD

**Issue by gakonst** [mersinvald/aquamarine#28]
Aquamarine uses Mermaid v9.1.5. 

In [this](https://github.com/gakonst/aquamarine-repro) minimal repro we're using some mermaid syntax which only was made available in later versions (correctly renders on Mermaid Live)

Recommended Fix:
Update mermaid version in https://github.com/mersinvald/aquamarine/tree/master/doc/js to latest. https://github.com/mermaid-js/mermaid/releases

**Comment by mersinvald** [comment]
Hi @gakonst. Could you please test [this branch](https://github.com/mersinvald/aquamarine/tree/feat/mermaidjs-9.3.0) on your case and tell me how it goes?

**Comment by gakonst** [comment]
Yup confirming it worked, e.g. my repro now renders! Send it!

![image](https://user-images.githubusercontent.com/17802178/215835600-5ec5393a-ffec-4895-b2e8-1ab73ccb1b79.png)
