### ISSUE TITLE
Leftmost part of the graph not visible sometimes

### ISSUE THREAD

**Issue by mgr-inz-rafal** [mersinvald/aquamarine#30]
Hello,
For some of the flowcharts, the leftmost part is not visible when embedded into the docs. Can we overcome that?

![image](https://user-images.githubusercontent.com/22395284/211347929-a95fba92-7ff2-4356-8d78-b09fb31775cf.png)

**Comment by mersinvald** [comment]
Could you please give me a reproducible example?

**Comment by mgr-inz-rafal** [comment]
Yes, certainly.
This is the code graph source code:
```
 flowchart TD
     style Start fill:#66ccff,stroke:#333,stroke-width:4px
     style End fill:#66ccff,stroke:#333,stroke-width:4px
     
     Start --> Initialize
     Initialize --> CatchUp
     CatchUp --> KeepUp
     KeepUp --> CatchUp
     KeepUp --> Validate
     Validate --> KeepUp
     CatchUp --> ShutdownForUpgrade
     KeepUp --> ShutdownForUpgrade
     Validate --> ShutdownForUpgrade
     CatchUp --> Upgrading
     CatchUp -->|at genesis| Validate
     Upgrading --> CatchUp
     ShutdownForUpgrade --> End
```

and this is the pic embededd in docs:

![image](https://user-images.githubusercontent.com/22395284/215745375-74fe847e-76ce-4f0d-953b-2bc081ced027.png)

**Comment by mersinvald** [comment]
@mgr-inz-rafal it doesn't reproduce for me locally with `cargo doc --open`. Does it break for you locally?
Is that a public crate I could see docs.rs page for?

<img width="847" alt="image" src="https://user-images.githubusercontent.com/8722061/215748290-ee2b4723-726e-421a-8b4f-2d1797660173.png">

**Comment by mgr-inz-rafal** [comment]
Yes, it reproduces for me locally in both Chrome and Firefox on Linux Mint.

The repo is public:
https://github.com/casper-network/casper-node

However, the docs are not yet published. The charts are merged into the `dev` branch.

This file contains the mentioned graph: https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/reactor_state.rs

**Comment by mersinvald** [comment]
@mgr-inz-rafal add the following init line in your flowchart declaration:

```
/// flowchart TD
///     %%{init: { 'flowchart': {'diagramPadding':100} }}%%
///     style Start fill:#66ccff,stroke:#333,stroke-width:4px
///     style End fill:#66ccff,stroke:#333,stroke-width:4px
///     
```

It would ensure you have padding at all borders, including leftmost. That should fix it.
Please let me know if that's not a one-off issue, in this case I think aquamarine should enforce larger padding on all diagram types by default.

**Comment by mersinvald** [comment]
Marking wontfix for now, will reopen if there are more occasions of this issue.

**Comment by mgr-inz-rafal** [comment]
@mersinvald Adding the manual padding worked like a charm, thanks! :+1:
