### ISSUE TITLE
Creates `target/doc` in the wrong directory

### ISSUE THREAD

**Issue by dpc** [mersinvald/aquamarine#38]
When used in in a sub-crate of a larger workspace, when running `cargo test` a file is created:

```
./<sub-crate-dir>/target/doc/mermaid.min.js
```

instead of expected `./target/doc/mermaid.min.js` for the whole workspace.

Seems to be caused by: https://github.com/mersinvald/aquamarine/blob/636675ba342a37a2a0aa87eb9adeea5c266f505c/src/attrs.rs#L140

Possibly `CARGO_TARGET_DIR` should be used instead as per https://doc.rust-lang.org/cargo/reference/environment-variables.html ?

**Comment by frehberg** [comment]
thanks for filing the issue. You are right "cargo test" should not generate the file target/doc/mermaid.min.js. 

In fact the file should be created only and only if invoking "cargo doc" 

No file should be created invoking "cargo test" as the tests do not require the JS package.

**Comment by frehberg** [comment]
Fixing this issue https://github.com/mersinvald/aquamarine/pull/36/commits
* extract only if target/doc exists (created when calling "cargo doc")
* do not extract if already exists

**Comment by frehberg** [comment]
has been fixed in newly released version 0.3.1
https://crates.io/crates/aquamarine/0.3.1

**Comment by frehberg** [comment]
as with release aquamarine 0.3.1 this issue has been solved

**Comment by frehberg** [comment]
as with release aquamarine 0.3.1 this issue has been solved
