### ISSUE TITLE
Move away from `proc-macro-error`

### ISSUE THREAD

**Issue by lovesegfault** [mersinvald/aquamarine#45]
Since `proc-macro-error` is unmaintained/abandoned, and depends on the legacy `syn 1`, it's probably a good idea to move away from it.

It seems like the likely successor is [`manyhow`](https://crates.io/crates/manyhow), though the API differs significantly.

**Comment by jayvdb** [comment]
c.f. https://github.com/rustsec/advisory-db/pull/2057
