### ISSUE TITLE
Why is version 0.4.0 yanked?

### ISSUE THREAD

**Issue by jplatte** [mersinvald/aquamarine#48]
Hi, I recently published a crate ([`matrix-sdk`](https://crates.io/crates/matrix-sdk/0.7.0)) that depends on v0.4 of `aquamarine`. Shortly after, the only release in the 0.4.x range was yanked. This is resulting in problems for anybody who is trying to use `matrix-sdk`.

Why was the crate yanked, and would you consider un-yanking it?

**Comment by mersinvald** [comment]
Hi @jplatte, it was due to a critical bug that affects crates that are downstream to those that use aquamarine. More details are in PR #47 and the related issues.

You should consider using `0.5.x` if you're utilizing `include_mmd!` macro.

**Comment by mersinvald** [comment]
Please let me know if bumping to `0.5.x` isn't possible for you, I'll un-yank the `0.4` in this case.

**Comment by jplatte** [comment]
The dependency is already bumped, but the release process is somewhat annoying and I prefer not having to do it again. The crate in question does not use `include_mmd!`.

C.f. [when to yank](https://doc.rust-lang.org/cargo/commands/cargo-yank.html#when-to-yank)

**Comment by bertybuttface** [comment]
> Please let me know if bumping to `0.5.x` isn't possible for you, I'll un-yank the `0.4` in this case.

Could you please un-yank `0.4`

**Comment by mersinvald** [comment]
@jplatte @bertybuttface sorry for the inconvenience, best intentions and all that :)

0.4.0 is un-yanked
