### ISSUE TITLE
Cut new release 

### ISSUE THREAD

**Issue by jmg-duarte** [mersinvald/aquamarine#53]
Hey @mersinvald! Long time no see! Hope you're doing well!

Your crate is a depedency of a really large project and one of the reasons said project is pulling syn 1 is this crate.

However, https://github.com/mersinvald/aquamarine/pull/52 upgraded the transitive dependency on syn and so, cutting a new release would make it one less crate pulling syn 1 when a bunch of others are pulling syn 2.

Thanks!

**Comment by mersinvald** [comment]
@jmg-duarte long time indeed, sorry, no time for anything these days :)

Published 0.6 to address the dependency graph issue, however i didn't update the bundled mermaidjs.

@frehberg could you please take the bundled update to 0.11? 
I'm not very sure how packaging of the bundled mermaidjs works now.
